In [ ]:
# creating list of even integers
intList = list(range(2, 101, 2))
print(intList, "\n")

# squared list
squaredList = [x**2 for x in intList]
print(squaredList)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100] 

[4, 16, 36, 64, 100, 144, 196, 256, 324, 400, 484, 576, 676, 784, 900, 1024, 1156, 1296, 1444, 1600, 1764, 1936, 2116, 2304, 2500, 2704, 2916, 3136, 3364, 3600, 3844, 4096, 4356, 4624, 4900, 5184, 5476, 5776, 6084, 6400, 6724, 7056, 7396, 7744, 8100, 8464, 8836, 9216, 9604, 10000]


In [ ]:
import numpy as np

# creating numpy array
arr = np.array([1, 2, 3, 4])
print(arr, "\n")

# creating array using numpy range
int_arr = np.arange(10)
print(int_arr, "\n")

numpPyArr = np.array(intList)  # converted normal python list into numpy array
print(numpPyArr)

[1 2 3 4] 

[0 1 2 3 4 5 6 7 8 9] 

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [ ]:
# converting numpy array directly to cubic array
cubic_arr = arr**3
print("Cubic Array: ", cubic_arr)

Cubic Array:  [ 1  8 27 64]


In [ ]:
# creating random numbers array
random_arr = np.random.rand(2, 3)
print(random_arr)

# normally distributed random numbers
rand_norm = np.random.randn(1, 4)
print(f"\nNormally distributed random Numbers: {rand_norm}")

[[0.89291487 0.03853202 0.36047452]
 [0.76171726 0.57420084 0.77772673]]

Normally distributed random Numbers: [[-0.24285502 -0.06814817  1.52031667 -1.1854692 ]]


In [ ]:
# checking data type
print("Data type: ", random_arr.dtype)

# checking length of array
print("Length of an array: ", rand_norm.size)

# checking dimensions of array
print("Dimesions: ", rand_norm.ndim)

# checking shape of an array
print("Shape: ", random_arr.shape)  # 2 rows and three columns

Data type:  float64
Length of an array:  4
Dimesions:  2
Shape:  (2, 3)


In [ ]:
# creating 3d array
# array of 4 rows, 5 columns, and 3 copies rand(copies, 4 rows, 5 columns)  --->> 3d array
arr_3d = np.random.rand(3, 4, 5)
print(arr_3d)

[[[0.68295283 0.7325002  0.11989897 0.72648654 0.72110897]
  [0.50989759 0.12068118 0.87516081 0.7420291  0.84097086]
  [0.10795116 0.33668127 0.42818362 0.15996202 0.18881861]
  [0.59070697 0.27410356 0.30871618 0.52022148 0.24310687]]

 [[0.79826022 0.43434571 0.07937107 0.53785985 0.75030728]
  [0.46188068 0.14808265 0.18766818 0.04191338 0.99186293]
  [0.45633397 0.48490721 0.93865718 0.78921703 0.71099956]
  [0.50841431 0.86470703 0.3683041  0.53898914 0.14402081]]

 [[0.54898046 0.3841099  0.68399168 0.28338961 0.87661227]
  [0.03815863 0.7878741  0.90158613 0.52511339 0.52574591]
  [0.11243817 0.30336324 0.37713988 0.78737514 0.38045563]
  [0.03235286 0.47471662 0.01358355 0.87905709 0.68386537]]]


In [ ]:
# breaking range of array into 3d array
arr3d = np.arange(24).reshape(
    2, 3, 4
)  # the elements should be adjusted in dimesion other will return an error
print(arr3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
arr3d = np.arange(24).reshape(2, 3, 4)
print(arr3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
# creating zeros array
zerosArr = np.zeros((3, 4))
print(zerosArr)

# creating ones array
onesArr = np.ones((2, 4, 5))
print(onesArr)

"""ones and zeros methods take tuple as input so we use double brackets"""

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


'ones and zeros methods take tuple as input so we use double brackets'

In [ ]:
# creating identical matrix
identicalArr = np.eye(5, 5)
identicalArr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# multiplying ones array by any number
multiples_arr = np.ones((4, 5)) * 12
multiples_arr

array([[12., 12., 12., 12., 12.],
       [12., 12., 12., 12., 12.],
       [12., 12., 12., 12., 12.],
       [12., 12., 12., 12., 12.]])

In [52]:
# full method is used to create array of specific number
x=7
arr=np.full((4,5),x)
arr


array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [57]:
arr2d1=np.arange(20).reshape(4,5)
print(arr2d1,"\n")
arr2d2=np.arange(20,40).reshape(4,5)
print(arr2d2,"\n")

# addition of 2 arrays
newArr=arr2d1+arr2d2
print("array after addition:\n",newArr)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

[[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]] 

array after addition:
 [[20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]
 [50 52 54 56 58]]


In [ ]:
# subtraction of two arrays of multiple copies
arr2d1=np.arange(36).reshape(3,3,4)
print("arr1: ",arr2d1,"\n\n")
arr2d2=np.arange(36,72).reshape(3,3,4)
print("arr2: ",arr2d2,"\n\n")

# addition of 2 arrays
newArr=arr2d1+arr2d2
print("array after subtraction:\n",newArr)

In [73]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[3])
print(arr[2:5])
print(arr[-5])
print(arr[:-2])

4
[3 4 5]
3
[1 2 3 4 5]


In [ ]:
# 2d slicing
arr=np.arange(20).reshape(4,5)
print(arr,"\n")

# slicing
slicedArr = arr[1:3,1:4]
print(slicedArr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

[[ 6  7  8]
 [11 12 13]]
