In [1]:
import numpy as np

# creating numpy array
arr = np.array([1, 2, 3, 4])
print(arr, "\n")

# creating array using numpy range
int_arr = np.arange(10)
print(int_arr, "\n")

intList = [1,2,4,5,6]
numpPyArr = np.array(intList)  # converted normal python list into numpy array
print(numpPyArr)

[1 2 3 4] 

[0 1 2 3 4 5 6 7 8 9] 

[1 2 4 5 6]


In [2]:
# converting numpy array directly to cubic array
cubic_arr = arr**3
print("Cubic Array: ", cubic_arr)

Cubic Array:  [ 1  8 27 64]


In [3]:
# creating random numbers array
random_arr = np.random.rand(2, 3)
print(random_arr)

# normally distributed random numbers
rand_norm = np.random.randn(4)
print(f"\nNormally distributed random Numbers: \n{rand_norm}")

[[0.37857266 0.67197261 0.65240974]
 [0.21825253 0.99613056 0.89306758]]

Normally distributed random Numbers: 
[-0.09160236  1.37068963 -0.90009966  2.15289429]


In [4]:
# checking data type
print("Data type: ", random_arr.dtype)

# checking length of array
print("Length of an array: ", random_arr.size)

# checking dimensions of array
print("Dimesions: ", random_arr.ndim)

# checking shape of an array
print("Shape: ", random_arr.shape)  # 2 rows and three columns

Data type:  float64
Length of an array:  6
Dimesions:  2
Shape:  (2, 3)


In [5]:
# creating 3d array
# array of 4 rows, 5 columns, and 3 copies rand(copies, 4 rows, 5 columns)  --->> 3d array
arr_3d = np.random.rand(3, 4, 5)
print(arr_3d)
print(arr_3d.size)

[[[0.59820603 0.50303949 0.23187622 0.80252478 0.54146139]
  [0.01288344 0.39602636 0.2927637  0.06871289 0.41945396]
  [0.4594604  0.19158618 0.50725772 0.19490469 0.89660654]
  [0.02488014 0.64027027 0.96316521 0.69540671 0.99913818]]

 [[0.3950239  0.77034631 0.11161201 0.30064724 0.2107249 ]
  [0.57724907 0.62381964 0.30076309 0.33461619 0.08992466]
  [0.69233402 0.55911254 0.28001005 0.47491935 0.35762183]
  [0.1649384  0.71214336 0.94838989 0.89196987 0.6114993 ]]

 [[0.55208776 0.96788439 0.80599402 0.65774656 0.32570124]
  [0.72121946 0.42004564 0.1677233  0.7127702  0.29030727]
  [0.70475596 0.48454055 0.19160273 0.43919911 0.47714027]
  [0.86396131 0.68322493 0.41993516 0.43170709 0.7984799 ]]]
60


In [6]:
# creating zeros array
zerosArr = np.zeros((3, 4))  # double parenthesis are for multi dimesional array. For single, use np.zeros(7)
print(zerosArr,"\n")

# creating ones array
onesArr = np.ones((2, 4, 5),dtype=int)
print(onesArr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [7]:
# creating identical matrix
# np.eye(N, M=None, k=0, dtype=float)
# N = Number of rows
# M = Number of columns
# k = 0, diagonal starting index

identicalArr = np.eye(5, 5, dtype=int)
identicalArr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [8]:
# multiplying ones array by any number
multiples_arr = np.ones((4, 5),dtype=int) * 12
multiples_arr

array([[12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12]])

In [9]:
# full method is used to create array of specific number
x=7
arr=np.full((4,5),x)
arr


array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [10]:
arr2d1=np.arange(20).reshape(4,5)
print(arr2d1,"\n")
arr2d2=np.arange(20,40).reshape(4,5)
print(arr2d2,"\n")

# addition of 2 arrays
newArr=arr2d1+arr2d2
print("array after addition:\n",newArr)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

[[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]] 

array after addition:
 [[20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]
 [50 52 54 56 58]]


In [11]:
# subtraction of two arrays of multiple copies
arr2d1=np.arange(36).reshape(3,3,4)
print("arr1:\n",arr2d1,"\n\n")
arr2d2=np.arange(36,72).reshape(3,3,4)
print("arr2:\n",arr2d2,"\n\n")

# subtraction of 2 arrays
newArr=arr2d2-arr2d1
print("array after subtraction:\n",newArr)

arr1:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]] 


arr2:
 [[[36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]]

 [[60 61 62 63]
  [64 65 66 67]
  [68 69 70 71]]] 


array after subtraction:
 [[[36 36 36 36]
  [36 36 36 36]
  [36 36 36 36]]

 [[36 36 36 36]
  [36 36 36 36]
  [36 36 36 36]]

 [[36 36 36 36]
  [36 36 36 36]
  [36 36 36 36]]]


In [12]:
# checking dimensions
a=np.array([[[[[[[[[[[[[[[[[[[[23]]]]]]]]]]]]]]]]]]]])
a.ndim

20

In [13]:
# Taking transpose of an array
arr2 = np.arange(36).reshape(6,6)
print(arr2)
arr2.T  # transpose

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


array([[ 0,  6, 12, 18, 24, 30],
       [ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35]])

In [14]:
# comparing values of arrays and finding maximum from them
# np.maximum() only accepts two arrays at a time, not three.

x=np.random.randn(8)
print(x)
y=np.random.randn(8)
print(y)

max = np.maximum(x,y)
print(max)

[-0.22819087 -0.44718648 -0.58677108 -2.48878892  0.36032493  0.38473887
 -0.97656433 -0.48131944]
[ 1.18641409 -0.97160752  0.42851659 -0.38785569 -0.82785397 -0.25784109
 -1.28007217 -0.66145773]
[ 1.18641409 -0.44718648  0.42851659 -0.38785569  0.36032493  0.38473887
 -0.97656433 -0.48131944]


In [15]:
arr = np.random.randn(8)
print(arr)

# splitting fractional and whole part
remainder, whole_part = np.modf(arr)
print("Franctional part:\n",remainder)
print("whole part:\n",whole_part)

[-1.0444258   0.11832635  0.36157387 -0.04627716 -0.56247515  0.48305907
  0.90237579  0.41249536]
Franctional part:
 [-0.0444258   0.11832635  0.36157387 -0.04627716 -0.56247515  0.48305907
  0.90237579  0.41249536]
whole part:
 [-1.  0.  0. -0. -0.  0.  0.  0.]


In [16]:
arr = np.array([2,3,4])  # only 3 elements, no columns and no rows
arr.shape

(3,)

In [17]:
# type casting
numArr = np.array([1,2,3,4])
print(numArr.dtype)
strArr = numArr.astype(str)
print(strArr)

int64
['1' '2' '3' '4']


In [18]:
# checking null values
arr= np.array([1,2,3,9,np.nan, 54, np.nan])
print(np.isnan(arr))  # returns boolean array

[False False False False  True False  True]


In [19]:
# filling null values
cleaned_arr = np.nan_to_num(arr, nan=4).astype(int)  # filling missing value with 4
cleaned_arr

array([ 1,  2,  3,  9,  4, 54,  4])

In [20]:
# checking infinite values
arr = np.array([2,3,np.inf,7,9, -np.inf])
print(arr)
print(np.isinf(arr)) # returns boolean array

# replacing infinite values
cleaned_arr = np.nan_to_num(arr, posinf=2, neginf=3).astype(int)  # replace positive infinite number with 2 and negative with 3
print("After replacing infinite values\n",cleaned_arr)

[  2.   3.  inf   7.   9. -inf]
[False False  True False False  True]
After replacing infinite values
 [2 3 2 7 9 3]
