# **Boolean masking**
- Used to filter arrays based on conditions

In [1]:
import numpy as np

In [14]:
arr = np.array(range(20))
print(arr[arr%5==0])

print(arr[arr%2==0])

print(arr[arr%2==1])

print(arr[(arr>5) & (arr<15)])

[ 0  5 10 15]
[ 0  2  4  6  8 10 12 14 16 18]
[ 1  3  5  7  9 11 13 15 17 19]
[ 6  7  8  9 10 11 12 13 14]


## **Practice Questions**

In [ ]:
# 1. Replace negative values with 0
arr = arr = np.array([2, -3, 5, -7, 9, -1])
arr[arr<0] = 0
print(arr)

[2 0 5 0 9 0]


In [ ]:
# 2. Extract values between 10 and 30 (inclusive)
arr = np.array([5, 10, 15, 20, 25, 30, 35])
arr = arr[(arr>=10) & (arr<=30)]
print(arr)

[10 15 20 25 30]


In [9]:
# 3. Count how many values are greater than 50
arr = np.random.randint(0, 100, size=20)
print(arr)
vals_greater_than_50 = arr[arr>50].size
print(f"{vals_greater_than_50} values are greater than 50")

[64 69 66  1 54  5 70 27 10 65 12 44  0 33 44 68 17  0 19  5]
7 values are greater than 50


In [20]:
# 4. Create a mask array of True for multiples of 3
arr = np.arange(1, 21)
boolean_mask_arr_for_3 = arr%3==0
print(boolean_mask_arr_for_3)

[False False  True False False  True False False  True False False  True
 False False  True False False  True False False]


In [24]:
# 5. Filter rows where age > 18 and score > 75
ages = np.array([15, 19, 22, 18, 21])
scores = np.array([80, 60, 90, 76, 85])

filtered_ages = ages[(ages>18) & (scores>75)]
filtered_scores = scores[(ages>18) & (scores>75)]

combined_arr = np.vstack((filtered_ages,filtered_scores))
print(combined_arr)

[[22 21]
 [90 85]]


In [25]:
# 6. Set all odd numbers to -1
arr = np.array([3, 4, 5, 6, 7, 8, 9])
print(arr)
arr[arr%2==1] = -1
print(arr)

[3 4 5 6 7 8 9]
[-1  4 -1  6 -1  8 -1]


In [30]:
# 7. Get indices of elements greater than the mean
arr = np.random.randint(1, 100, size=10)
print(arr)
mean = np.mean(arr)
print(f"Mean value of the above array: {mean}")
indexes = np.where(arr>mean)
indexes

[ 3 54 41 58 49 62 91 31 81  3]
Mean value of the above array: 47.3


(array([1, 3, 4, 5, 6, 8]),)