# **Broadcasting**
##### - Broadcasting is a powerful feature in NumPy that lets you perform arithmetic operations on arrays of different shapes without writing explicit loops. Instead of manually looping through elements of arrays with mismatched shapes, NumPy automatically "stretches" the smaller array to match the larger one where possible.

## ✅ Rules of Broadcasting
When operating on two arrays, NumPy compares their shapes from right to left. Two dimensions are compatible if:

- They are equal, or
- It expands smaller arrays into larger arrays
- One of them is 1
- If dimensions are not compatible, NumPy raises an error.

In [2]:
import numpy as np

### Scalar with Array

In [3]:
prices = np.array([200,250,450,730])

discount_percent = 10  # 10 percent discount on every product

final_prices = (prices - (prices*discount_percent)/100).astype(int)
print(final_prices)

[180 225 405 657]


In [8]:
arr = np.arange(3,15,2)
print(arr)
squares_arr = arr **2
print(squares_arr)

[ 3  5  7  9 11 13]
[  9  25  49  81 121 169]


### Broadcasting from 1d to 2d array

In [4]:
matrix = np.arange(15).reshape(3,5)
vector = np.array([13,12,18,3,11])
addition = matrix + vector
print(addition)

[[13 13 20  6 15]
 [18 18 25 11 20]
 [23 23 30 16 25]]


In [ ]:
arr = np.arange(15).reshape(5,3)
vector = [1,2,3,4]
subtraction = arr-vector
print(subtraction)  ## error: broadcasting not possible