# **Linear Algebra**

In [2]:
import numpy as np

In [3]:
x=np.array([[1,2,3],[7,8,9]])
y=np.array([[2,3],[-1,7],[8,9]])
print(x)
print(y)

[[1 2 3]
 [7 8 9]]
[[ 2  3]
 [-1  7]
 [ 8  9]]


In [4]:
## Matrix Multiplication
dot_product = x@y
print(dot_product)

"""Note: The number of columns of first matrix should be equal to the number of rows of second matrix"""

[[ 24  44]
 [ 78 158]]


'Note: The number of columns of first matrix should be equal to the number of rows of second matrix'

In [5]:
# other methods for doing multiplication
print(x.dot(y))
print(np.dot(x,y))

[[ 24  44]
 [ 78 158]]
[[ 24  44]
 [ 78 158]]


In [17]:
x= np.random.randint(1, 21, size=25).reshape(5,5)
print(x)

# doing multiple operations on a single variable
matrix = x.T  # 1st transpose of x
print(matrix)

# multiply transpose of x with original matrix x
multiple = matrix@x
multiple

[[20 17 16 12 14]
 [15  1  4  5 11]
 [ 5  8 19 13 19]
 [15  2 10  8 15]
 [12  5 15  1  6]]
[[20 15  5 15 12]
 [17  1  8  2  5]
 [16  4 19 10 15]
 [12  5 13  8  1]
 [14 11 19 15  6]]


array([[1019,  485,  805,  512,  837],
       [ 485,  383,  523,  334,  461],
       [ 805,  523,  958,  554,  869],
       [ 512,  334,  554,  403,  596],
       [ 837,  461,  869,  596,  939]], dtype=int32)

In [ ]:
# inverse of a matrix
from numpy.linalg import inv

a=np.arange(0,4).reshape(2,2)
print(a)
inverse = inv(a)
print(inverse)

[[0 1]
 [2 3]]
[[-1.5  0.5]
 [ 1.   0. ]]


In [ ]:
# finding detereminant
print(np.linalg.det(a))

-2.0
