# **Linear Algebra**

In [2]:
import numpy as np

In [3]:
x=np.array([[1,2,3],[7,8,9]])
y=np.array([[2,3],[-1,7],[8,9]])
print(x)
print(y)

[[1 2 3]
 [7 8 9]]
[[ 2  3]
 [-1  7]
 [ 8  9]]


In [4]:
## Matrix Multiplication
dot_product = x@y
print(dot_product)

"""Note: The number of columns of first matrix should be equal to the number of rows of second matrix"""

[[ 24  44]
 [ 78 158]]


'Note: The number of columns of first matrix should be equal to the number of rows of second matrix'

In [5]:
# other methods for doing multiplication
print(x.dot(y))
print(np.dot(x,y))

[[ 24  44]
 [ 78 158]]
[[ 24  44]
 [ 78 158]]


In [6]:
x=np.random.randn(5,5)

# doing multiple operations on a single variable
mat = x.T.dot(x)  # 1st transpose of x, then multiplied transpose with x
mat

array([[ 1.612988  ,  0.7135927 ,  1.68051487,  0.41843226,  0.60359994],
       [ 0.7135927 ,  1.06765346,  0.51215243, -1.00936209, -0.88295946],
       [ 1.68051487,  0.51215243,  3.08840437,  0.9104232 ,  1.71552748],
       [ 0.41843226, -1.00936209,  0.9104232 ,  4.69187964,  2.96270925],
       [ 0.60359994, -0.88295946,  1.71552748,  2.96270925,  3.66914383]])

In [7]:
# inverse of a matrix
from numpy.linalg import inv

a=np.arange(0,4).reshape(2,2)
print(a)
inverse = inv(a)
print(inverse)

[[0 1]
 [2 3]]
[[-1.5  0.5]
 [ 1.   0. ]]


In [8]:
# finding detereminant
print(np.linalg.det(a))

-2.0
