# **Linear Algebra**

In [2]:
import numpy as np

In [3]:
x=np.array([[1,2,3],[7,8,9]])
y=np.array([[2,3],[-1,7],[8,9]])
print(x)
print(y)

[[1 2 3]
 [7 8 9]]
[[ 2  3]
 [-1  7]
 [ 8  9]]


In [ ]:
## Matrix Multiplication
dot_product = x@y
print(dot_product)

"""Note: The number of columns of first matrix should be equal to the number of rows of second matrix"""

[[ 24  44]
 [ 78 158]]


'Note: The number of columns of first matrix should be equal to the number of rows of second matrix'

In [5]:
# other methods for doing multiplication
print(x.dot(y))
print(np.dot(x,y))

[[ 24  44]
 [ 78 158]]
[[ 24  44]
 [ 78 158]]


In [9]:
x=np.random.randn(5,5)

# doing multiple operations on a single variable
mat = x.T.dot(x)  # 1st transpose of x, then multiplied transpose with x
mat

array([[ 4.1835019 , -0.1583423 ,  4.32908712, -0.65615965,  1.334536  ],
       [-0.1583423 ,  0.38907078, -0.72185769,  0.35795673, -0.23179247],
       [ 4.32908712, -0.72185769,  6.80769877,  0.13324633,  1.22151846],
       [-0.65615965,  0.35795673,  0.13324633,  1.91059758, -1.59746262],
       [ 1.334536  , -0.23179247,  1.22151846, -1.59746262,  2.84711922]])

In [7]:
# inverse of a matrix
from numpy.linalg import inv

a=np.arange(0,4).reshape(2,2)
print(a)
inverse = inv(a)
print(inverse)

[[0 1]
 [2 3]]
[[-1.5  0.5]
 [ 1.   0. ]]


In [8]:
# finding detereminant
print(np.linalg.det(a))

-2.0
