In [2]:
# creating list of even integers
intList = list(range(2, 101, 2))
print(intList, "\n")

# squared list
squaredList = [x**2 for x in intList]
print(squaredList)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100] 

[4, 16, 36, 64, 100, 144, 196, 256, 324, 400, 484, 576, 676, 784, 900, 1024, 1156, 1296, 1444, 1600, 1764, 1936, 2116, 2304, 2500, 2704, 2916, 3136, 3364, 3600, 3844, 4096, 4356, 4624, 4900, 5184, 5476, 5776, 6084, 6400, 6724, 7056, 7396, 7744, 8100, 8464, 8836, 9216, 9604, 10000]


In [3]:
import numpy as np

# creating numpy array
arr = np.array([1, 2, 3, 4])
print(arr, "\n")

# creating array using numpy range
int_arr = np.arange(10)
print(int_arr, "\n")

numpPyArr = np.array(intList)  # converted normal python list into numpy array
print(numpPyArr)

[1 2 3 4] 

[0 1 2 3 4 5 6 7 8 9] 

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [4]:
# converting numpy array directly to cubic array
cubic_arr = arr**3
print("Cubic Array: ", cubic_arr)

Cubic Array:  [ 1  8 27 64]


In [5]:
# creating random numbers array
random_arr = np.random.rand(2, 3)
print(random_arr)

# normally distributed random numbers
rand_norm = np.random.randn(1, 4)
print(f"\nNormally distributed random Numbers: {rand_norm}")

[[0.26794717 0.75727665 0.46726494]
 [0.41132879 0.46779039 0.58710876]]

Normally distributed random Numbers: [[-0.79599479 -2.48454567 -0.11756341 -0.0448076 ]]


In [6]:
# checking data type
print("Data type: ", random_arr.dtype)

# checking length of array
print("Length of an array: ", rand_norm.size)

# checking dimensions of array
print("Dimesions: ", rand_norm.ndim)

# checking shape of an array
print("Shape: ", random_arr.shape)  # 2 rows and three columns

Data type:  float64
Length of an array:  4
Dimesions:  2
Shape:  (2, 3)


In [7]:
# creating 3d array
# array of 4 rows, 5 columns, and 3 copies rand(copies, 4 rows, 5 columns)  --->> 3d array
arr_3d = np.random.rand(3, 4, 5)
print(arr_3d)

[[[0.15101132 0.91885332 0.09784405 0.30854359 0.17516427]
  [0.44218492 0.04546731 0.59767391 0.7837212  0.53650848]
  [0.7393106  0.78430166 0.71445095 0.97901947 0.37029916]
  [0.06137976 0.29897676 0.71953763 0.03173587 0.55508112]]

 [[0.45694661 0.19620449 0.45643119 0.61227019 0.3454212 ]
  [0.6832662  0.91478713 0.93938796 0.13269593 0.33330287]
  [0.46849968 0.99915554 0.0755951  0.12957121 0.42059701]
  [0.36727279 0.96702954 0.63813052 0.41890595 0.0038337 ]]

 [[0.79000019 0.67872359 0.1485238  0.57651905 0.59216622]
  [0.74505046 0.69635676 0.52713678 0.44424286 0.44035745]
  [0.95274599 0.89518707 0.22954206 0.11432353 0.29886746]
  [0.99777263 0.9488284  0.9655657  0.378769   0.42678165]]]


In [8]:
# breaking range of array into 3d array
arr3d = np.arange(24).reshape(
    2, 3, 4
)  # the elements should be adjusted in dimesion other will return an error
print(arr3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [9]:
arr3d = np.arange(24).reshape(2, 3, 4)
print(arr3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [10]:
# creating zeros array
zerosArr = np.zeros((3, 4))
print(zerosArr)

# creating ones array
onesArr = np.ones((2, 4, 5))
print(onesArr)

"""ones and zeros methods take tuple as input so we use double brackets"""

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


'ones and zeros methods take tuple as input so we use double brackets'

In [11]:
# creating identical matrix
identicalArr = np.eye(5, 5)
identicalArr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
# multiplying ones array by any number
multiples_arr = np.ones((4, 5)) * 12
multiples_arr

array([[12., 12., 12., 12., 12.],
       [12., 12., 12., 12., 12.],
       [12., 12., 12., 12., 12.],
       [12., 12., 12., 12., 12.]])

In [13]:
# full method is used to create array of specific number
x=7
arr=np.full((4,5),x)
arr


array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [14]:
arr2d1=np.arange(20).reshape(4,5)
print(arr2d1,"\n")
arr2d2=np.arange(20,40).reshape(4,5)
print(arr2d2,"\n")

# addition of 2 arrays
newArr=arr2d1+arr2d2
print("array after addition:\n",newArr)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

[[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]] 

array after addition:
 [[20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]
 [50 52 54 56 58]]


In [15]:
# subtraction of two arrays of multiple copies
arr2d1=np.arange(36).reshape(3,3,4)
print("arr1: ",arr2d1,"\n\n")
arr2d2=np.arange(36,72).reshape(3,3,4)
print("arr2: ",arr2d2,"\n\n")

# addition of 2 arrays
newArr=arr2d1+arr2d2
print("array after subtraction:\n",newArr)

arr1:  [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]] 


arr2:  [[[36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]]

 [[60 61 62 63]
  [64 65 66 67]
  [68 69 70 71]]] 


array after subtraction:
 [[[ 36  38  40  42]
  [ 44  46  48  50]
  [ 52  54  56  58]]

 [[ 60  62  64  66]
  [ 68  70  72  74]
  [ 76  78  80  82]]

 [[ 84  86  88  90]
  [ 92  94  96  98]
  [100 102 104 106]]]


In [16]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[3])
print(arr[2:5])
print(arr[-5])
print(arr[:-2])

4
[3 4 5]
3
[1 2 3 4 5]


In [17]:
# 2d slicing
arr=np.arange(20).reshape(4,5)
print(arr,"\n")

slicedArr = arr[1:3,1:4]  # rows 1 and 2, columns 1,2 and 3
print(slicedArr)
arr[2,2:4]  # 2nd row, columns 2 and 3

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

[[ 6  7  8]
 [11 12 13]]


array([12, 13])

In [18]:
arr2d = np.arange(64).reshape(8,8)
print(arr2d,"\n")
print(arr2d[4:7, 3:7],"\n")

print(arr2d[4,:])
print(arr2d[4:5,:])
print(arr2d[:,5])
print(arr2d[:,5:6])
print(arr2d[4:7,3:7])
print(arr2d[::2])
print(arr2d[::-2])
print(arr2d[5,4])
print(arr2d[5:6,4:5])

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]] 

[[35 36 37 38]
 [43 44 45 46]
 [51 52 53 54]] 

[32 33 34 35 36 37 38 39]
[[32 33 34 35 36 37 38 39]]
[ 5 13 21 29 37 45 53 61]
[[ 5]
 [13]
 [21]
 [29]
 [37]
 [45]
 [53]
 [61]]
[[35 36 37 38]
 [43 44 45 46]
 [51 52 53 54]]
[[ 0  1  2  3  4  5  6  7]
 [16 17 18 19 20 21 22 23]
 [32 33 34 35 36 37 38 39]
 [48 49 50 51 52 53 54 55]]
[[56 57 58 59 60 61 62 63]
 [40 41 42 43 44 45 46 47]
 [24 25 26 27 28 29 30 31]
 [ 8  9 10 11 12 13 14 15]]
44
[[44]]


In [19]:
# checking dimensions
a=np.array([[[[[[[[[[[[[[[[[[[[23]]]]]]]]]]]]]]]]]]]])
a.ndim

20

In [20]:
arr = np.array(range(20))
print(arr[arr%5==0])

print(arr[arr%2==0])

print(arr[arr%2==1])

print(arr[(arr>5) & (arr<15)])

[ 0  5 10 15]
[ 0  2  4  6  8 10 12 14 16 18]
[ 1  3  5  7  9 11 13 15 17 19]
[ 6  7  8  9 10 11 12 13 14]


In [21]:
import numpy as np
arr2 = np.arange(36).reshape(6,6)
print(arr2)
arr2.T  # transpose

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


array([[ 0,  6, 12, 18, 24, 30],
       [ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35]])

In [30]:
arr =np.arange(20)
print(arr)
print(np.round(np.sqrt(arr),2))
# print(np.exp(arr))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0.   1.   1.41 1.73 2.   2.24 2.45 2.65 2.83 3.   3.16 3.32 3.46 3.61
 3.74 3.87 4.   4.12 4.24 4.36]


In [23]:
x=np.random.randn(8)
print(x)
y=np.random.randn(8)
print(y)
max = np.maximum(x,y)
print(max)

[ 1.39343316 -1.18521931 -1.00681769  0.57035452  0.78775573 -1.25174841
  1.11258168  0.18995637]
[-0.61785168 -0.91846754  1.03923176  0.73264658  1.65800792 -0.09968038
  0.57501251 -0.2283298 ]
[ 1.39343316 -0.91846754  1.03923176  0.73264658  1.65800792 -0.09968038
  1.11258168  0.18995637]


In [ ]:
arr = np.random.randn(8)
print(arr)

# splitting fractional and whole part
remainder, whole_part = np.modf(arr)
print(remainder)
print(whole_part)

# assigning both remainder and whole part in a single variable
whole_part=np.modf(arr)
print(whole_part)

[-0.68073463 -0.03547269 -0.40959464  0.19085284 -0.03003771  1.25196989
 -0.1258404   1.23302078]
[-0.68073463 -0.03547269 -0.40959464  0.19085284 -0.03003771  0.25196989
 -0.1258404   0.23302078]
[-0. -0. -0.  0. -0.  1. -0.  1.]
(array([-0.68073463, -0.03547269, -0.40959464,  0.19085284, -0.03003771,
        0.25196989, -0.1258404 ,  0.23302078]), array([-0., -0., -0.,  0., -0.,  1., -0.,  1.]))
