In [4]:
import numpy as np

# creating numpy array
arr = np.array([1, 2, 3, 4])
print(arr, "\n")

# creating array using numpy range
int_arr = np.arange(10)
print(int_arr, "\n")

intList = [1,2,4,5,6]
numpPyArr = np.array(intList)  # converted normal python list into numpy array
print(numpPyArr)

[1 2 3 4] 

[0 1 2 3 4 5 6 7 8 9] 

[1 2 4 5 6]


In [ ]:
# converting numpy array directly to cubic array
cubic_arr = arr**3
print("Cubic Array: ", cubic_arr)

Cubic Array:  [ 1  8 27 64]


In [ ]:
# creating random numbers array
random_arr = np.random.rand(2, 3)
print(random_arr)

# normally distributed random numbers
rand_norm = np.random.randn(4)
print(f"\nNormally distributed random Numbers: \n{rand_norm}")

[[0.71637308 0.76910472 0.01692254]
 [0.53588077 0.68588457 0.82309858]]

Normally distributed random Numbers: 
[ 0.70749345  0.61618326 -0.42363888 -2.6918414 ]


In [ ]:
# checking data type
print("Data type: ", random_arr.dtype)

# checking length of array
print("Length of an array: ", random_arr.size)

# checking dimensions of array
print("Dimesions: ", rand_norm.ndim)

# checking shape of an array
print("Shape: ", random_arr.shape)  # 2 rows and three columns

Data type:  float64
Length of an array:  6
Dimesions:  1
Shape:  (2, 3)


In [ ]:
# creating 3d array
# array of 4 rows, 5 columns, and 3 copies rand(copies, 4 rows, 5 columns)  --->> 3d array
arr_3d = np.random.rand(3, 4, 5)
print(arr_3d)
print(arr_3d.size)

[[[0.73142233 0.91808749 0.0335138  0.79665107 0.55446049]
  [0.88439834 0.48774566 0.98463707 0.56460212 0.78133182]
  [0.72682894 0.97293069 0.22620742 0.20951655 0.10466444]
  [0.02589072 0.71911776 0.24311434 0.47365597 0.16531577]]

 [[0.30361119 0.37236804 0.30490419 0.4187637  0.91020878]
  [0.83142551 0.65168533 0.66373971 0.24831624 0.33805717]
  [0.88718536 0.7159548  0.91917041 0.7670191  0.39799738]
  [0.83469042 0.6228763  0.0846629  0.27421244 0.29773282]]

 [[0.45150603 0.68061802 0.4371944  0.46339202 0.31157947]
  [0.19011877 0.55254431 0.21713603 0.97167563 0.66658182]
  [0.48400145 0.97377042 0.39644728 0.96404166 0.35171505]
  [0.08371223 0.11543067 0.31683322 0.0108816  0.21650741]]]
60


In [ ]:
# creating zeros array
zerosArr = np.zeros((3, 4))  # double parenthesis are for multi dimesional array. For single, use np.zeros(7)
print(zerosArr,"\n")

# creating ones array
onesArr = np.ones((2, 4, 5),dtype=int)
print(onesArr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [ ]:
# creating identical matrix
# np.eye(N, M=None, k=0, dtype=float)
# N = Number of rows
# M = Number of columns
# k = 0, diagonal starting index

identicalArr = np.eye(5, 5, dtype=int)
identicalArr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
# multiplying ones array by any number
multiples_arr = np.ones((4, 5),dtype=int) * 12
multiples_arr

array([[12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12]])

In [ ]:
# full method is used to create array of specific number
x=7
arr=np.full((4,5),x)
arr


array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [ ]:
arr2d1=np.arange(20).reshape(4,5)
print(arr2d1,"\n")
arr2d2=np.arange(20,40).reshape(4,5)
print(arr2d2,"\n")

# addition of 2 arrays
newArr=arr2d1+arr2d2
print("array after addition:\n",newArr)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

[[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]] 

array after addition:
 [[20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]
 [50 52 54 56 58]]


In [ ]:
# subtraction of two arrays of multiple copies
arr2d1=np.arange(36).reshape(3,3,4)
print("arr1: ",arr2d1,"\n\n")
arr2d2=np.arange(36,72).reshape(3,3,4)
print("arr2: ",arr2d2,"\n\n")

# addition of 2 arrays
newArr=arr2d1+arr2d2
print("array after subtraction:\n",newArr)

arr1:  [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]] 


arr2:  [[[36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]]

 [[60 61 62 63]
  [64 65 66 67]
  [68 69 70 71]]] 


array after subtraction:
 [[[ 36  38  40  42]
  [ 44  46  48  50]
  [ 52  54  56  58]]

 [[ 60  62  64  66]
  [ 68  70  72  74]
  [ 76  78  80  82]]

 [[ 84  86  88  90]
  [ 92  94  96  98]
  [100 102 104 106]]]


In [ ]:
# checking dimensions
a=np.array([[[[[[[[[[[[[[[[[[[[23]]]]]]]]]]]]]]]]]]]])
a.ndim

20

In [3]:
# Numpy Boolean masking (used to filter arrays based on conditions)

arr = np.array(range(20))
print(arr[arr%5==0])

print(arr[arr%2==0])

print(arr[arr%2==1])

print(arr[(arr>5) & (arr<15)])

[ 0  5 10 15]
[ 0  2  4  6  8 10 12 14 16 18]
[ 1  3  5  7  9 11 13 15 17 19]
[ 6  7  8  9 10 11 12 13 14]


In [ ]:
# Taking transpose of an array
arr2 = np.arange(36).reshape(6,6)
print(arr2)
arr2.T  # transpose

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


array([[ 0,  6, 12, 18, 24, 30],
       [ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35]])

In [ ]:
# comparing values of arrays and finding maximum from them
x=np.random.randn(8)
print(x)
y=np.random.randn(8)
print(y)
z=np.random.randn(8)
print(z)
max = np.maximum(x,y,z)
print(max)

[-0.75148771 -1.15363222 -0.31860309 -0.80128954 -0.1568895   0.82008572
  1.93126422  0.71883688]
[ 1.07845822  0.65366366  0.98505977  0.74778267 -0.91346183  0.02805946
  0.23647857  0.65405236]
[ 0.58712584  0.57490885 -0.9734269   0.71682855  0.73842514  0.30202106
 -0.13149245  0.20931604]
[ 1.07845822  0.65366366  0.98505977  0.74778267 -0.1568895   0.82008572
  1.93126422  0.71883688]


In [ ]:
arr = np.random.randn(8)
print(arr)

# splitting fractional and whole part
remainder, whole_part = np.modf(arr)
print(remainder)
print(whole_part)

# assigning both remainder and whole part in a single variable
whole_part=np.modf(arr)
print(whole_part)

[ 0.04550496  0.42152054 -1.94577288  0.06182088 -0.39062682  1.11999623
 -0.03816892  0.72445096]
[ 0.04550496  0.42152054 -0.94577288  0.06182088 -0.39062682  0.11999623
 -0.03816892  0.72445096]
[ 0.  0. -1.  0. -0.  1. -0.  0.]
(array([ 0.04550496,  0.42152054, -0.94577288,  0.06182088, -0.39062682,
        0.11999623, -0.03816892,  0.72445096]), array([ 0.,  0., -1.,  0., -0.,  1., -0.,  0.]))


In [ ]:
arr = np.array([2,3,4])  # only 3 elements, no columns and no rows
arr.shape

(3,)

In [ ]:
# type casting
numArr = np.array([1,2,3,4])
print(numArr.dtype)
strArr = numArr.astype(str)
print(strArr)

int64
['1' '2' '3' '4']
