In [2]:
import numpy as np

# creating numpy array
arr = np.array([1, 2, 3, 4])
print(arr, "\n")

# creating array using numpy range
int_arr = np.arange(10)
print(int_arr, "\n")

intList = [1,2,4,5,6]
numpPyArr = np.array(intList)  # converted normal python list into numpy array
print(numpPyArr)

[1 2 3 4] 

[0 1 2 3 4 5 6 7 8 9] 

[1 2 4 5 6]


In [3]:
# converting numpy array directly to cubic array
cubic_arr = arr**3
print("Cubic Array: ", cubic_arr)

Cubic Array:  [ 1  8 27 64]


In [4]:
# creating random numbers array
random_arr = np.random.rand(2, 3)
print(random_arr)

# normally distributed random numbers
rand_norm = np.random.randn(4)
print(f"\nNormally distributed random Numbers: \n{rand_norm}")

[[0.87562856 0.89790341 0.36986414]
 [0.5643626  0.87461037 0.08181871]]

Normally distributed random Numbers: 
[ 1.68853946  0.20130832  0.58289421 -0.29892251]


In [5]:
# checking data type
print("Data type: ", random_arr.dtype)

# checking length of array
print("Length of an array: ", random_arr.size)

# checking dimensions of array
print("Dimesions: ", rand_norm.ndim)

# checking shape of an array
print("Shape: ", random_arr.shape)  # 2 rows and three columns

Data type:  float64
Length of an array:  6
Dimesions:  1
Shape:  (2, 3)


In [6]:
# creating 3d array
# array of 4 rows, 5 columns, and 3 copies rand(copies, 4 rows, 5 columns)  --->> 3d array
arr_3d = np.random.rand(3, 4, 5)
print(arr_3d)
print(arr_3d.size)

[[[0.08125262 0.22730365 0.65310988 0.8085239  0.91646604]
  [0.96118298 0.03888433 0.2218198  0.47946558 0.64426723]
  [0.89078048 0.45431438 0.69543171 0.80790188 0.47397534]
  [0.33468077 0.91459109 0.30784734 0.51112535 0.34048204]]

 [[0.91606342 0.24464991 0.99358179 0.90220017 0.35297591]
  [0.43171449 0.8176396  0.05157749 0.29085351 0.2828901 ]
  [0.93027138 0.01317894 0.58474334 0.95570826 0.3188519 ]
  [0.30045553 0.19566496 0.35482386 0.93126005 0.53215221]]

 [[0.21047775 0.69732529 0.91835881 0.63400091 0.55839046]
  [0.41799489 0.02824387 0.79886509 0.4007375  0.7203079 ]
  [0.41834104 0.35170073 0.76371458 0.56037314 0.40514253]
  [0.99944254 0.83289797 0.29717006 0.45646765 0.19231717]]]
60


In [7]:
# creating zeros array
zerosArr = np.zeros((3, 4))  # double parenthesis are for multi dimesional array. For single, use np.zeros(7)
print(zerosArr,"\n")

# creating ones array
onesArr = np.ones((2, 4, 5),dtype=int)
print(onesArr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [8]:
# creating identical matrix
# np.eye(N, M=None, k=0, dtype=float)
# N = Number of rows
# M = Number of columns
# k = 0, diagonal starting index

identicalArr = np.eye(5, 5, dtype=int)
identicalArr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [9]:
# multiplying ones array by any number
multiples_arr = np.ones((4, 5),dtype=int) * 12
multiples_arr

array([[12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12]])

In [10]:
# full method is used to create array of specific number
x=7
arr=np.full((4,5),x)
arr


array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [11]:
arr2d1=np.arange(20).reshape(4,5)
print(arr2d1,"\n")
arr2d2=np.arange(20,40).reshape(4,5)
print(arr2d2,"\n")

# addition of 2 arrays
newArr=arr2d1+arr2d2
print("array after addition:\n",newArr)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

[[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]] 

array after addition:
 [[20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]
 [50 52 54 56 58]]


In [22]:
# subtraction of two arrays of multiple copies
arr2d1=np.arange(36).reshape(3,3,4)
print("arr1:\n",arr2d1,"\n\n")
arr2d2=np.arange(36,72).reshape(3,3,4)
print("arr2:\n",arr2d2,"\n\n")

# subtraction of 2 arrays
newArr=arr2d2-arr2d1
print("array after subtraction:\n",newArr)

arr1:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]] 


arr2:
 [[[36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]]

 [[60 61 62 63]
  [64 65 66 67]
  [68 69 70 71]]] 


array after subtraction:
 [[[36 36 36 36]
  [36 36 36 36]
  [36 36 36 36]]

 [[36 36 36 36]
  [36 36 36 36]
  [36 36 36 36]]

 [[36 36 36 36]
  [36 36 36 36]
  [36 36 36 36]]]


In [13]:
# checking dimensions
a=np.array([[[[[[[[[[[[[[[[[[[[23]]]]]]]]]]]]]]]]]]]])
a.ndim

20

In [14]:
# Numpy Boolean masking (used to filter arrays based on conditions)

arr = np.array(range(20))
print(arr[arr%5==0])

print(arr[arr%2==0])

print(arr[arr%2==1])

print(arr[(arr>5) & (arr<15)])

[ 0  5 10 15]
[ 0  2  4  6  8 10 12 14 16 18]
[ 1  3  5  7  9 11 13 15 17 19]
[ 6  7  8  9 10 11 12 13 14]


In [15]:
# Taking transpose of an array
arr2 = np.arange(36).reshape(6,6)
print(arr2)
arr2.T  # transpose

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


array([[ 0,  6, 12, 18, 24, 30],
       [ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35]])

In [23]:
# comparing values of arrays and finding maximum from them
# np.maximum() only accepts two arrays at a time, not three.

x=np.random.randn(8)
print(x)
y=np.random.randn(8)
print(y)

max = np.maximum(x,y)
print(max)

[ 1.67874051  2.19063249 -0.3503333   0.83863407  0.60893149  1.39916427
 -0.67044979 -0.36590393]
[-2.72425106  0.51573146  0.15668054 -4.2023899  -1.23122282 -0.39470238
  0.77762672  0.61065595]
[1.67874051 2.19063249 0.15668054 0.83863407 0.60893149 1.39916427
 0.77762672 0.61065595]


In [28]:
arr = np.random.randn(8)
print(arr)

# splitting fractional and whole part
remainder, whole_part = np.modf(arr)
print("Franctional part:\n",remainder)
print("whole part:\n",whole_part)

[-0.53771449  0.1227311  -1.95313699 -2.35241506  0.18296071 -0.0931553
  0.57703245  0.22714032]
Franctional part:
 [-0.53771449  0.1227311  -0.95313699 -0.35241506  0.18296071 -0.0931553
  0.57703245  0.22714032]
whole part:
 [-0.  0. -1. -2.  0. -0.  0.  0.]


In [18]:
arr = np.array([2,3,4])  # only 3 elements, no columns and no rows
arr.shape

(3,)

In [19]:
# type casting
numArr = np.array([1,2,3,4])
print(numArr.dtype)
strArr = numArr.astype(str)
print(strArr)

int64
['1' '2' '3' '4']
