# Reshaping 
### changing dimension of array without modifying its elements

In [2]:
import numpy as np

In [3]:
arr = np.arange(64)
print(arr)

# now reshaping arr
reshaped_arr = arr.reshape(4,16) # 4 x 16 = 64
print(reshaped_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63]]


In [4]:
new_arr = np.arange(12)
print("\n",new_arr)
new_arr.reshape(2,3,2) # here the first index is using for copies


 [ 0  1  2  3  4  5  6  7  8  9 10 11]


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [25]:
# breaking range of array into 3d array
arr3d = np.arange(24).reshape(
    2, 3, 4
)  # the elements should be adjusted in dimesion other will return an error
print(arr3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


## Convert multi dimensional array into 1D Array

In [ ]:
# 1st method: "ravel": it modifies original array
arr1d = arr3d.ravel()
arr1d[0]=334
print(arr1d)
print(arr3d)  # original array is also modified

[334   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23]
[[[334   1   2   3]
  [  4   5   6   7]
  [  8   9  10  11]]

 [[ 12  13  14  15]
  [ 16  17  18  19]
  [ 20  21  22  23]]]


In [ ]:
arr1d=arr3d.flatten()  # it makes copy of the original array
arr1d[1] = 8882
print(arr1d)
print(arr3d)  # here the original array is not modified

[ 334 8882    2    3    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23]
[[[334   1   2   3]
  [  4   5   6   7]
  [  8   9  10  11]]

 [[ 12  13  14  15]
  [ 16  17  18  19]
  [ 20  21  22  23]]]
