In [44]:
import numpy as np

# **General Syntax**
- array[row_start : row_stop : row_step, col_start : col_stop : col_step]

In [45]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[3])
print(arr[2:5])
print(arr[-5])
print(arr[:-2])
print(arr[::-1])  # reversed array

4
[3 4 5]
3
[1 2 3 4 5]
[7 6 5 4 3 2 1]


In [46]:
# 2d slicing
arr2d=np.arange(20).reshape(4,5)
print(arr2d,"\n")

slicedArr = arr2d[1:3,1:4]  # rows 1 and 2, columns 1,2 and 3
print(slicedArr)
arr2d[2,2:4]  # 2nd row, columns 2 and 3

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

[[ 6  7  8]
 [11 12 13]]


array([12, 13])

## **New Array**

In [47]:
arr2d_new = np.arange(64).reshape(8,8)
print(arr2d_new)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]


In [48]:
print(arr2d_new[4:7, 3:7])

[[35 36 37 38]
 [43 44 45 46]
 [51 52 53 54]]


In [49]:
print(arr2d_new[4,:])  # All columns of 4th row
print(arr2d_new[4:5,:]) # same result but in 2d array

[32 33 34 35 36 37 38 39]
[[32 33 34 35 36 37 38 39]]


In [50]:
print(arr2d_new[:,5])  # 5th column of all rows
print(arr2d_new[:,5:6]) # Same result but in 2d

[ 5 13 21 29 37 45 53 61]
[[ 5]
 [13]
 [21]
 [29]
 [37]
 [45]
 [53]
 [61]]


In [51]:
print(arr2d_new[::2]) # every 2nd row, starting from the first row (index 0).

[[ 0  1  2  3  4  5  6  7]
 [16 17 18 19 20 21 22 23]
 [32 33 34 35 36 37 38 39]
 [48 49 50 51 52 53 54 55]]


In [52]:
print(arr2d_new[::-2]) # every second row starting from second last 

[[56 57 58 59 60 61 62 63]
 [40 41 42 43 44 45 46 47]
 [24 25 26 27 28 29 30 31]
 [ 8  9 10 11 12 13 14 15]]


In [53]:
print(arr2d_new[:,::2])  # every second column of each row

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]
 [48 50 52 54]
 [56 58 60 62]]


In [54]:
print(arr2d_new[::2,::2]) # every second row and every second column

[[ 0  2  4  6]
 [16 18 20 22]
 [32 34 36 38]
 [48 50 52 54]]


In [55]:
print(arr2d_new[4:8:2, 1:7:3]) # every third row between 4 to 8 and every third column between 1 to 7

[[33 36]
 [49 52]]


In [56]:
print(arr2d_new[5,4])  # fifth row, 4th column
print(arr2d_new[5:6,4:5])  # Same result but in 2d

44
[[44]]


## **Fancy Indexing**
### Selecting multiple elements at once

In [57]:
fancy_arr = np.array([2,3,1,4,6,7])

print(fancy_arr[[1,5,3]])

[3 7 4]


In [58]:
# fancy indexing on 2d array
fancy_2d_arr = np.arange(21,41).reshape(4,5)
print(fancy_2d_arr)

[[21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]]


In [ ]:
# specific rows: row 1 and 3
print(fancy_2d_arr[[1,3]])  

[[36 37 38 39 40]
 [26 27 28 29 30]]


In [ ]:
# Fancy index columns only
print(fancy_2d_arr[:, [2,0]])  # all rows and columns 2 and 0

[[23 21]
 [28 26]
 [33 31]
 [38 36]]


In [67]:
# Fancy index specific (row,column) pairs
print(fancy_2d_arr[[3,1,0],[2,4,0]])

# First array: rows [3,1,0]
# Second array: columns [2,4,0]
# It picks: (3,2), (1,4), (0,0)

[38 30 21]
