# **insert method**
- np.insert(array, index_num, value, axis=None)

### we can perform insert operation in the copy of the original array
array - original array<br>
index<br>
value<br>
axis = 0 for row wise data and axis = 1 for column wise(2d) data, by default it inserts row wise

In [2]:
import numpy as np

In [3]:
arr=np.arange(10)
print(arr)

new_arr = np.insert(arr, 5, 8786)
print(new_arr)

[0 1 2 3 4 5 6 7 8 9]
[   0    1    2    3    4 8786    5    6    7    8    9]


## to insert element in 2d array

In [4]:
arr_2d = np.arange(20).reshape(5,4)
print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [5]:
# insert a new row at index 2
new_arr_2d = np.insert(arr_2d,2,[100,200,300,400], axis=0) # axis = 0 for row wise insertion
print(new_arr_2d)

[[  0   1   2   3]
 [  4   5   6   7]
 [100 200 300 400]
 [  8   9  10  11]
 [ 12  13  14  15]
 [ 16  17  18  19]]


In [6]:
new_arr_2d = np.insert(arr_2d,3,[100,200,300,400,500], axis=1)  # axis = 1 for column wise insertion at index 3 of each row 
print(new_arr_2d)

[[  0   1   2 100   3]
 [  4   5   6 200   7]
 [  8   9  10 300  11]
 [ 12  13  14 400  15]
 [ 16  17  18 500  19]]


In [9]:
# axis = None for flatten array
# new_arr_2d = np.insert(arr, 1, 6, axis=None)
new_arr_2d = np.insert(arr, 1, [8,3,2], axis=None)
print(new_arr_2d)

[0 8 3 2 1 2 3 4 5 6 7 8 9]


## append: adds element at the end of array

In [8]:
new_arr = np.append(arr, [100,150])
print(new_arr)

[  0   1   2   3   4   5   6   7   8   9 100 150]


## join two or more arrays using concatenate

In [11]:
arr1 = np.arange(5)
arr2 = np.arange(5,11)
new_arr = np.concatenate((arr1,arr2))
new_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## remove element at specific index

In [12]:
new_arr = np.delete(arr1, 2)
new_arr

array([0, 1, 3, 4])

## remove element from 2d array

In [18]:
arr_2d = np.arange(20).reshape(4,5)
print(arr_2d)
updated_arr = np.delete(arr_2d, 1, axis=0)  # axis 0 for removing row 
print("updated array\n",updated_arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
updated array
 [[ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
updated_arr  = np.delete(arr_2d,[2,0], axis=0)  # remove row 0 and 2
print(updated_arr)

[[ 5  6  7  8  9]
 [15 16 17 18 19]]


In [ ]:
updated_arr = np.delete(arr_2d,1,axis=1)  # removes column 1 (1,6,11,16)
print(updated_arr)

[[ 0  2  3  4]
 [ 5  7  8  9]
 [10 12 13 14]
 [15 17 18 19]]


In [24]:
updated_arr = np.delete(arr_2d,[2,4],axis=1) # remove column 2 and 4
print(updated_arr)

[[ 0  1  3]
 [ 5  6  8]
 [10 11 13]
 [15 16 18]]


## **vstack():**  vertically stack  
## **hstack():**  horizontally stack

In [31]:
arr1 = np.arange(5)
arr2 = np.arange(5,10)

vertical_stack = np.vstack((arr1,arr2))
print("vertical_stack:\n",vertical_stack)
horizontal_stack = np.hstack((arr1,arr2))
print("\nhorizontal_stack:\n",horizontal_stack)

vertical_stack:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

horizontal_stack:
 [0 1 2 3 4 5 6 7 8 9]


## **split**
- np.split(array, how_many_parts)

In [35]:
arr = np.arange(10)
first_part, second_part = np.split(arr,2)  
print(first_part)
print(second_part)

[0 1 2 3 4]
[5 6 7 8 9]
